# Generated by Django 3.0.14 on 2022-01-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleGeneModel',
        ),
        migrations.DeleteModel(
            name='ExampleLoopModel',
        ),
        migrations.DeleteModel(
            name='ExamplePeakModel',
        ),
    ]
