# Generated by Django 3.0.14 on 2022-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0002_auto_20220124_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleGeneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdbid', models.SlugField(default='CDBG00000001')),
                ('geneID', models.CharField(default=None, max_length=50)),
                ('genesymbol', models.CharField(default=None, max_length=50)),
                ('geneposition', models.CharField(default=None, max_length=50)),
                ('chromosome', models.CharField(default=None, max_length=50)),
                ('start', models.IntegerField(default=None)),
                ('end', models.IntegerField(default=None)),
                ('strand', models.CharField(default=None, max_length=5)),
                ('proteincoding', models.CharField(default=None, max_length=50)),
                ('triplewheter', models.BooleanField(default=None)),
                ('triplecohesin', models.TextField(default=None)),
                ('relatedtype', models.CharField(default=None, max_length=50)),
                ('loopwhether', models.BooleanField(default=None)),
                ('looptype', models.CharField(default=None, max_length=50)),
                ('loopstudy', models.TextField(default=None)),
                ('loopsubunit', models.CharField(default=None, max_length=50)),
                ('degwhether', models.BooleanField(default=None)),
                ('degnumberstudy', models.IntegerField(default=None)),
                ('degstudy', models.TextField(default=None)),
                ('degsubunit', models.CharField(default=None, max_length=50)),
                ('correlationwhether', models.BooleanField(default=None)),
                ('correlationRho', models.FloatField(default=None)),
                ('correlationFDR', models.FloatField(default=None)),
                ('correlationsubunit', models.TextField(default=None)),
            ],
            options={
                'ordering': ('geneposition',),
            },
        ),
        migrations.CreateModel(
            name='ExampleLoopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdbid', models.SlugField(default='CDBL00000002')),
                ('chrom1', models.CharField(max_length=50)),
                ('start1', models.IntegerField()),
                ('end1', models.IntegerField()),
                ('chrom2', models.CharField(max_length=50)),
                ('start2', models.IntegerField()),
                ('end2', models.IntegerField()),
                ('assay', models.CharField(max_length=100)),
                ('subunit', models.CharField(max_length=100)),
                ('celltype', models.CharField(max_length=1000)),
                ('study', models.TextField()),
                ('looplength', models.IntegerField()),
                ('loopwidth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamplePeakModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdbid', models.SlugField(default='CDBP00000001')),
                ('chromosome', models.CharField(default=None, max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('slug', models.SlugField(max_length=100)),
                ('datasource', models.TextField()),
                ('celltype', models.TextField()),
                ('cellspecificity', models.FloatField()),
                ('subunit', models.CharField(max_length=1000)),
                ('CTCFdependent', models.CharField(max_length=20)),
                ('location', models.CharField(default=None, max_length=20)),
                ('boundary', models.CharField(max_length=20)),
                ('hubs', models.CharField(max_length=20)),
                ('hicloop', models.CharField(default=None, max_length=20)),
                ('hicchiploop', models.CharField(default=None, max_length=20)),
                ('chialoop', models.CharField(default=None, max_length=20)),
                ('enhancer', models.CharField(max_length=20)),
                ('cobind', models.TextField()),
                ('targetgene', models.TextField()),
                ('targetgeneID', models.TextField()),
                ('snp', models.TextField()),
                ('codingmut', models.IntegerField(default=None)),
                ('noncodingmut', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ('chromosome', 'start'),
            },
        ),
    ]
