# Generated by Django 3.0.14 on 2022-01-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0003_examplegenemodel_exampleloopmodel_examplepeakmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTExData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdbid', models.SlugField(default='CDBGTEX00001')),
                ('geneID', models.CharField(default=None, max_length=50)),
                ('genesymbol', models.CharField(default=None, max_length=50)),
                ('gini', models.FloatField(default=None)),
                ('tissuename', models.TextField()),
                ('tissuemedian', models.TextField()),
            ],
        ),
    ]
