# Generated by Django 3.0.14 on 2022-01-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0004_gtexdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='link',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
