# Generated by Django 3.0.14 on 2022-01-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0005_processeddata_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata',
            options={'ordering': ('-cdbid',)},
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='created',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='data_date',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='updated',
        ),
    ]
