# Generated by Django 3.0.14 on 2022-02-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0006_auto_20220128_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakmodel',
            name='peakoccupancy',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
