# Generated by Django 3.0.14 on 2022-02-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0007_peakmodel_peakoccupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplepeakmodel',
            name='peakoccupancy',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
