# Generated by Django 3.0.14 on 2022-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0008_examplepeakmodel_peakoccupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepeakmodel',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='peakmodel',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
