# Generated by Django 3.0.14 on 2022-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoSite', '0009_auto_20220205_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='content3',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
